//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace geos_mvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;


    public partial class personel
    {
        public int pers_id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Mail { get; set; }
        public string Gsm { get; set; }
        [DisplayName("Kullanıcı Adı")]
        [Required(ErrorMessage ="Lütfen Kullanıcı Adı Giriniz",AllowEmptyStrings =false)]
        public string KullanıcıAdı { get; set; }
        [DisplayName("Şifre")]
        [Required(ErrorMessage = "Lütfen Şifre Giriniz", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string Sifre { get; set; }
        public string LoginErrorMsg { get; set; }
    }
}
